### PR TITLE
GatoBot

### PR DESCRIPTION
**Pull request by CattoDev**
this is probably the most horrible geode code ever
but it doesn't break compatibility so accept please k thx

### CODE REVIEW

**Comment by altalk23** [comment]
if the repo is public, can you share the link
if not, can you share the repo with one of the verified users to check the code

**Comment by CattoDev** [comment]
https://github.com/cattodev/gatobot

**Comment by altalk23** [comment]
```cpp
		auto modLib = GetModuleHandle("GatoBot.dll");
		if(!modLib) modLib = LoadLibraryA(dllPath.string().c_str());```
this is not acceptable

**Comment by CattoDev** [comment]
fair

**Comment by altalk23** [comment]
!reject

**Pull request closed without merging**
