### PR TITLE
Add/Update muhammadgames.bettermenu

### PR DESCRIPTION
**Pull request by MuhXd**
Source code is linked on the mod.
If it doesn't work here is the source code link: https://github.com/MuhXd/BetterMenuMod

### CODE REVIEW

**Comment by MuhXd** [comment]
Ah yea just in case here is the index
https://github.com/MuhXd/GeodeModIndexer

**Comment by FigmentBoy** [comment]
Hey! It looks good, I'd change the popup on the first launch to say which mod is causing it to appear.

**Comment by MuhXd** [comment]
oh ok will do as i was working on a update so i will make it do that

**Comment by MuhXd** [comment]
> Hey! It looks good, I'd change the popup on the first launch to say which mod is causing it to appear.

I have added it plus a setting to turn it off

**Comment by MuhXd** [comment]
> Hey! It looks good, I'd change the popup on the first launch to say which mod is causing it to appear.

image
image

**Comment by MuhXd** [comment]
also if anyone wants to use this mod while looking at this here is Version 1.0.4-Beta.2

https://github.com/MuhXd/BetterMenuMod/releases/download/Mac%2BPc-Build/muhammadgames.bettermenu.geode

**Comment by MuhXd** [comment]
> also if anyone wants to use this mod while looking at this here is Version 1.0.4-Beta.2
> 
> https://github.com/MuhXd/BetterMenuMod/releases/download/Mac%2BPc-Build/muhammadgames.bettermenu.geode

Updated and link will work

**Pull request closed without merging**
