### PR TITLE
Add ekv.hidePauseMenuHack

### PR DESCRIPTION
**Pull request by EKVgd**
My mod adding a button to the pause menu that lets you hide it.

### CODE REVIEW

**Comment by altalk23** [comment]
can you upload the source code?

**Comment by EKVgd** [comment]
Oh sure I am not that familiar with this GitHub thing I thought it already was. I will create a new repo and give you the link

**Comment by EKVgd** [comment]
Should be on my profile if that is the correct way to do it. https://gitHub.com/EKVgd/hidePauseMenuHack

**Comment by EKVgd** [comment]
I don't know what I did, I did something. Now my mod is not here anymore. I checked the publish mod page of the docs. They updated i assume? I couldn't find the command I used yesterday to publish so I did the issue thing I think. I will remove this fork I think.

**Comment by Weebifying** [comment]
what the hell...

**Comment by EKVgd** [comment]
Sorry I don't know what I am doing and how to publish mods.

**Comment by Weebifying** [comment]
?
image

**Comment by EKVgd** [comment]
I know but the website said something different yesterday and so I panicked and did some shit and I don't know how but I deleted some of my files and idk I did something

**Pull request closed without merging**
