### PR TITLE
Add/Update org.dogotrigger.deathreplay

### PR DESCRIPTION
**Pull request by SergeyMC9730**
**Source code**: https://github.com/SergeyMC9730/deathreplay

Also I need to explain why I wrote these lines:
Screenshot from 2023-09-02 15-23-32

Reason behind is simple: using DevTools I saw that required layer (`PlayLayer->[3] CCLayer`) for this mod doesn't have tag attached.

Screenshot from 2023-09-02 15-24-28

There is no way I could safely put my stuff into it. This is why I had to use child index to get required layer which is unsafe, I know. BUT I'll fix it when related patch for Geode would be released

Mod demonstration: https://youtu.be/q1bi3BiXVi4

For clarity, you change behaviour of this mod. You can enable/disable particles, music or even not show deaths at all.

<br>
my first mod

### CODE REVIEW

**Comment by HJfod** [comment]
I think getting by child index is acceptable in this case since the camera layer in PlayLayer should always be in the same place, do update when IDs get added tho

**Comment by matcool** [comment]
!accept

**Comment by matcool** [comment]
ok i dont think that will work so u will have to reopen. silly fod shouldnt have merged

**Comment by SergeyMC9730** [comment]
bruh

**Pull request merged**
