### PR TITLE
Add/Update gdutils

### PR DESCRIPTION
**Pull request by Jouca**
**Mod Download Link**
https://github.com/Jouca/GDUtils-Geode/releases/download/v1.0.0/gdutils.geode

**Mod Repo**
https://github.com/Jouca/GDUtils-Geode

### CODE REVIEW

**Comment by altalk23** [comment]
!reject prs are deprecated wait

**Comment by altalk23** [comment]
Make an issue with the mod link instead

**Comment by matcool** [comment]
!accept

**Comment by matcool** [comment]
!accept

**Comment by matcool** [comment]
!accept

**Comment by matcool** [comment]
!accept

**Pull request closed without merging**
